export const socialLinks = `<nav class="brand-socials" aria-label="Redes sociales de Cóndor AI">${[['Instagram','https://www.instagram.com/condor.ai/'],['TikTok','https://www.tiktok.com/@condor_ai'],['LinkedIn','https://www.linkedin.com/company/condorai-development/'],['Facebook','https://www.facebook.com/p/Condor-ai-61589812719000/']].map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${name}</a>`).join('')}</nav>`;
export const barbaraPlans = [
 {name:'Lite',price:'49.990',tag:'Para empezar a publicar en serio.',items:['12 carruseles al mes con tu paleta, tipografía y logo.','Captions con estructura y hashtags, listas para publicar.','Correcciones por chat: hasta 3 por pieza.','Aprende de tus preferencias y correcciones.']},
 {name:'Go',price:'89.990',tag:'Tu marca presente, cada semana.',items:['Todo lo de Lite.','20 historias al mes.','4 videos UGC: formato de persona presentando tu producto.','Mezcla de contenido a tu medida: educar, vender y mostrar tu marca.','Publicación automática en Instagram y Facebook, en el horario que elijas.']},
 {name:'Plus',price:'119.990',tag:'Más canales. Más acompañamiento.',items:['Todo lo de Go.','Revisión con IA antes de cada entrega.','Memoria de marca ampliada.','Prioridad en correcciones y reporte mensual.','Publicación multicanal: Instagram, TikTok, LinkedIn y Facebook.','Edición automática de video: subtítulos, cortes y ajustes básicos.']},
];
export const barbaraShowcase = `<section class="bb-showcase" id="barbara"><div class="wrap">
 <div class="bb-intro"><div><p class="bb-label">CONOCE A TU AGENTE DE CONTENIDO</p><h2>Bárbara<span>Tu marca tiene algo que decir.</span></h2><p>Bárbara crea contenido con la identidad de tu negocio. Le cuentas qué necesitas, revisas las piezas y pides cambios por chat. Según tu plan, también programa y publica en tus redes.</p><a class="btn bb-cta" href="#planes-barbara">Encuentra tu plan</a></div><img src="/assets/barbara/lockup.jpg" alt="Bárbara, tu agente de IA de contenido" width="1600" height="900" /></div>
 <div class="bb-plans" id="planes-barbara">${barbaraPlans.map((p,i)=>`<article class="bb-plan bb-plan-${i}"><p class="bb-label">${i===1?'PRESENCIA COMPLETA':i===2?'ACOMPAÑAMIENTO AMPLIADO':'TU PUNTO DE PARTIDA'}</p><h3>Bárbara ${p.name}</h3><p>${p.tag}</p><p class="bb-price">$${p.price}<small> CLP / mes</small></p><ul>${p.items.map(x=>`<li>${x}</li>`).join('')}</ul><a class="btn bb-cta" href="https://wa.me/56988989824?text=${encodeURIComponent('Hola, me interesa Bárbara '+p.name+' a $'+p.price+' CLP al mes. Quiero confirmar las condiciones y activar mi plan.')}" target="_blank" rel="noopener">Elegir ${p.name}</a></article>`).join('')}</div>
 <p class="bb-footnote">Todos los planes incluyen tu marca aplicada en cada pieza, soporte 24/7 y mejoras continuas del producto. La publicación requiere conectar y autorizar tus cuentas. Las revisiones ayudan a detectar errores; no reemplazan tu aprobación de contenido sensible.</p>
 <a class="bb-more" href="/productos/barbara/">Conoce cómo funciona Bárbara</a>
 </div></section>`;
