const socialMarks = {
 Instagram:'<rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.5" cy="6.5" r="1.2"/>',
 TikTok:'<path d="M15 2h3c.3 2.4 1.7 3.9 4 4.2v3.1a8.1 8.1 0 0 1-4-1.2v7.2a6.7 6.7 0 1 1-5.9-6.6V12a3.4 3.4 0 1 0 2.9 3.3V2Z"/>',
 LinkedIn:'<path d="M4 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4ZM2.3 9h3.4v12H2.3ZM9 9h3.3v1.7C13 9.5 14.2 9 15.8 9c3.2 0 4.2 2 4.2 5v7h-3.4v-6.3c0-1.5-.3-2.8-2-2.8s-2.2 1.3-2.2 2.8V21H9Z"/>',
 Facebook:'<path d="M14 22v-9h3l.5-3H14V8c0-.9.3-1.5 1.6-1.5h2V3.8c-.4-.1-1.6-.2-2.8-.2-2.8 0-4.6 1.7-4.6 4.8V10H7v3h3.2v9Z"/>'
};
export const socialLinks = `<nav class="brand-socials" aria-label="Redes sociales de Cóndor AI">${[['Instagram','https://www.instagram.com/condor.ai/'],['TikTok','https://www.tiktok.com/@condor_ai'],['LinkedIn','https://www.linkedin.com/company/condorai-development/'],['Facebook','https://www.facebook.com/p/Condor-ai-61589812719000/']].map(([name,url])=>`<a href="${url}" aria-label="${name}" title="${name}" target="_blank" rel="noopener noreferrer"><svg viewBox="0 0 24 24" width="17" height="17" fill="currentColor" aria-hidden="true">${socialMarks[name]}</svg></a>`).join('')}</nav>`;
export const barbaraPlans = [
 {name:'Lite',price:'49.990',tag:'Para empezar a publicar en serio.',items:['12 carruseles al mes con tu paleta, tipografía y logo.','Captions con estructura y hashtags, listas para publicar.','Correcciones por chat: hasta 3 por pieza.','Aprende de tus preferencias y correcciones.']},
 {name:'Go',price:'89.990',tag:'Tu marca presente, cada semana.',items:['Todo lo de Lite.','20 historias al mes.','4 videos UGC: formato de persona presentando tu producto.','Mezcla de contenido a tu medida: educar, vender y mostrar tu marca.','Publicación automática en Instagram y Facebook, en el horario que elijas.']},
 {name:'Plus',price:'119.990',tag:'Más canales. Más acompañamiento.',items:['Todo lo de Go.','Revisión con IA antes de cada entrega.','Memoria de marca ampliada.','Prioridad en correcciones y reporte mensual.','Publicación multicanal: Instagram, TikTok, LinkedIn y Facebook.','Edición automática de video: subtítulos, cortes y ajustes básicos.']},
];
export const barbaraShowcase = `<section class="bb-showcase" id="barbara"><div class="wrap">
 <div class="bb-intro"><div><p class="bb-label">CONOCE A TU AGENTE DE CONTENIDO</p><h2>Bárbara<span>Tu marca tiene algo que decir.</span></h2><p>Bárbara crea contenido con la identidad de tu negocio. Le cuentas qué necesitas, revisas las piezas y pides cambios por chat. Según tu plan, también programa y publica en tus redes.</p><a class="btn bb-cta" href="#planes-barbara">Encuentra tu plan</a></div><img src="/assets/barbara/lockup.jpg" alt="Bárbara, tu agente de IA de contenido" width="1600" height="900" /></div>
 <div class="bb-plans" id="planes-barbara">${barbaraPlans.map((p,i)=>`<article class="bb-plan bb-plan-${i}"><p class="bb-label">${i===1?'PRESENCIA COMPLETA':i===2?'ACOMPAÑAMIENTO AMPLIADO':'TU PUNTO DE PARTIDA'}</p><h3>Bárbara ${p.name}</h3><p>${p.tag}</p><p class="bb-price">$${p.price}<small> CLP / mes</small></p><ul>${p.items.map(x=>`<li>${x}</li>`).join('')}</ul><a class="btn bb-cta" href="https://wa.me/56988989824?text=${encodeURIComponent('Hola, me interesa Bárbara '+p.name+' a $'+p.price+' CLP al mes. Quiero confirmar las condiciones y activar mi plan.')}" target="_blank" rel="noopener">Elegir ${p.name}</a></article>`).join('')}</div>
 <p class="bb-footnote">Todos los planes incluyen tu marca aplicada en cada pieza, soporte 24/7 y mejoras continuas del producto. La publicación requiere conectar y autorizar tus cuentas. Las revisiones ayudan a detectar errores; no reemplazan tu aprobación de contenido sensible.</p>
 <a class="bb-more" href="/productos/barbara/">Conoce cómo funciona Bárbara</a>
 </div></section>`;
