export function trackLanding({cab,pie,jsComun}) {return cab({titulo:'Cóndor Track — Un CRM a la medida de tu negocio',desc:'Tu relación con cada cliente merece continuidad. Diseñamos un CRM a medida de tu proceso comercial, tus tareas y tu equipo.',ruta:'/productos/track/'})+`
<link rel="stylesheet" href="/rediseno/track.css?v=3" /><main class="track-page">
<section class="track-hero"><div class="wrap"><p class="track-brand"><img src="/assets/productos/condor-track-v3.png" width="52" height="52" alt="Cóndor Track" />Cóndor Track</p><p class="kicker">MENOS BUSCAR. MÁS AVANZAR.</p><h1>Cada cliente tiene una historia.<br><span>Que tu equipo pueda seguirla.</span></h1><p class="track-lead">Creemos que una oportunidad no debería perderse entre una planilla y un mensaje. Por eso construimos un CRM a la medida de cómo trabaja tu negocio.</p><div class="hero-cta"><a class="btn btn-primario" href="/agendar">Conversemos sobre tu proceso</a><a class="btn btn-linea" href="#track-modulos">Explora lo que podemos construir</a></div></div></section>
<section class="track-section"><div class="wrap track-split"><div><p class="kicker">01 / EL PUNTO DE PARTIDA</p><h2>Tu negocio no cabe<br>en una casilla genérica.</h2></div><div><p>Hay empresas que cotizan antes de vender. Otras coordinan visitas, siguen solicitudes o acompañan a sus clientes durante meses. Tu CRM debería reflejar ese recorrido.</p><p>Track reúne la información del cliente, el estado de cada oportunidad y el siguiente paso en un espacio diseñado para tu equipo. Empezamos por entender qué necesitan recordar, decidir y hacer cada día.</p><div class="track-example"><span>Un recorrido posible</span><p>Consulta → Contacto → Propuesta → Seguimiento → Cliente</p><small>Ejemplo de proceso; las etapas se definen contigo.</small></div></div></div></section>
<section class="track-section track-soft" id="track-modulos"><div class="wrap"><p class="kicker">02 / A TU MEDIDA</p><h2>Construimos lo que necesitas.<br>Lo demás puede esperar.</h2><p class="track-lead">Estos son módulos que podemos evaluar para tu CRM. El alcance, las integraciones y el costo se acuerdan antes de desarrollar.</p><div class="track-modules">
${[
['Clientes y contactos','Una ficha que reúna lo importante.','Datos de contacto, historial, notas y documentos relevantes. Definimos juntos qué información necesita tu equipo y quién puede consultarla.'],
['Oportunidades y ventas','Saber dónde está cada conversación.','Etapas comerciales propias, responsables, montos y próximos pasos para dar continuidad al seguimiento sin depender de la memoria de una persona.'],
['Tareas y recordatorios','Que el siguiente paso tenga dueño.','Actividades, fechas y asignaciones vinculadas a cada cliente u oportunidad. Podemos evaluar avisos según las necesidades y canales acordados.'],
['Cotizaciones y documentos','Conservar el contexto de cada propuesta.','Organizar propuestas, archivos y estados de aprobación. La generación de documentos o conexión con facturación se cotiza según el flujo requerido.'],
['Reportes para decidir','Ver lo que importa para tu operación.','Vistas de oportunidades, etapas, actividad y resultados basadas en los datos disponibles. Elegimos indicadores útiles para tu negocio, no un tablero lleno por llenar.'],
['Roles e integraciones','Un sistema que conviva con tu equipo.','Permisos según responsabilidades, importación de datos y conexiones con herramientas existentes. Revisamos APIs, autorizaciones y costos de terceros antes de comprometer una integración.'],
['Agentes de IA por chat','Cada conversación, conectada con el siguiente paso.','Podemos desarrollar agentes para responder consultas, recoger antecedentes, calificar oportunidades y coordinar citas en los canales acordados. La conversación puede alimentar el CRM y derivarse a una persona cuando requiere criterio o atención especial.'],
['Agentes de IA por llamada','La voz también puede formar parte de tu proceso.','Diseñamos flujos de atención y seguimiento por voz: recoger información, confirmar citas y registrar resultados en el CRM. Definimos identificación del agente, autorizaciones, límites de acción y transferencia a una persona; telefonía y consumo se detallan en la propuesta.'],
['Automatizaciones entre procesos','Que una acción active lo que viene después.','Asignar un responsable al llegar un lead, crear una tarea después de una llamada, preparar un borrador de propuesta o avisar de una oportunidad sin seguimiento. Acordamos reglas, aprobaciones humanas y manejo de errores para cada flujo.'],
['Software desarrollado desde cero','Si tu necesidad no está resuelta, podemos construirla.','Módulos propios, portales, herramientas internas y aplicaciones conectadas al CRM, o una solución independiente para tu operación. Diseñamos y desarrollamos desde cero cuando lo que ofrece el mercado no se ajusta a la necesidad de tu empresa.']
].map(([title,short,detail],i)=>`<details class="track-module"><summary><span class="track-number">${String(i+1).padStart(2,'0')}</span><h3>${title}</h3><p>${short}</p><span class="track-expand" aria-hidden="true">+</span></summary><p>${detail}</p></details>`).join('')}
</div></div></section>
<section class="track-section"><div class="wrap track-split"><div><p class="kicker">MÁS ALLÁ DE UN CRM</p><h2>Si no encuentras la herramienta,<br>construyamos la que necesitas.</h2></div><div><p>Tu forma de trabajar no debería quedar limitada por el catálogo de un software. Podemos desarrollar desde cero la solución que tu empresa necesita: dentro de Track o como una aplicación independiente.</p><p>Un portal para tus clientes, una herramienta interna, un flujo de aprobaciones o agentes de IA que conversen por chat y llamada. Partimos del problema, validamos la viabilidad y conectamos cada desarrollo con el resto de tu operación.</p><a class="btn btn-linea" href="/agendar">Cuéntanos lo que aún no has podido resolver</a></div></div></section>
<section class="track-section"><div class="wrap track-split"><div><p class="kicker">03 / CÓMO LO HACEMOS</p><h2>Primero tu proceso.<br>Después el software.</h2></div><ol class="track-process">
<li><h3>Entendemos cómo trabajan</h3><p>Revisamos el recorrido del cliente, la información que manejan y los puntos donde se pierde tiempo o contexto.</p></li>
<li><h3>Acordamos una primera versión</h3><p>Priorizamos los módulos, usuarios e integraciones. Recibes una propuesta con alcance, plazos, precio y condiciones antes de comenzar.</p></li>
<li><h3>Construimos y revisamos contigo</h3><p>Validamos pantallas y flujos con quienes usarán el CRM. Las decisiones se apoyan en situaciones reales de trabajo.</p></li>
<li><h3>Preparamos la puesta en marcha</h3><p>Acordamos la carga de datos, capacitación, accesos y soporte. Las nuevas etapas se planifican según lo que el negocio vaya necesitando.</p></li>
</ol></div></section>
<section class="track-section track-dark"><div class="wrap track-split"><div><p class="kicker">04 / ¿HACEMOS BUEN EQUIPO?</p><h2>Te va a hacer sentido<br>si quieres ordenar para crecer.</h2></div><div><p>Si estás dispuesto a mirar cómo trabaja tu negocio, a cuestionar pasos que ya no aportan y a involucrar a tu equipo en el cambio, tenemos una buena conversación pendiente.</p><p>Track puede encajar cuando necesitas un proceso propio y una construcción acompañada. Si hoy te basta una herramienta estándar lista para usar, también vale la pena reconocerlo antes de invertir.</p></div></div></section>
<section class="track-section" id="track-precio"><div class="wrap track-split"><div><p class="kicker">05 / UNA PROPUESTA CON ALCANCE</p><h2>Tu CRM empieza<br>por una conversación.</h2><p class="track-price">Desde $84.990 <small>CLP</small></p><p>Valor inicial referencial. Un CRM con más módulos, usuarios o integraciones puede tener un costo considerablemente mayor.</p><a class="btn btn-primario" href="/agendar">Definamos tu primera versión</a></div><div class="track-faq">
<details><summary>¿Qué incluye ese valor?</summary><p>No es un paquete de CRM completo ni una tarifa única. El entregable y su alcance se detallan en la cotización. Impuestos, modalidad de pago, hosting, licencias y soporte se especifican antes de contratar.</p></details>
<details><summary>¿Podemos partir con algo pequeño?</summary><p>Sí. Podemos definir una primera versión centrada en el problema prioritario y planificar módulos adicionales como etapas separadas.</p></details>
<details><summary>¿Podemos traer nuestras planillas?</summary><p>Evaluamos su estructura, calidad y volumen para proponer una migración. La limpieza de datos y la importación se incluyen solo si están contempladas en el alcance.</p></details>
<details><summary>¿Se conecta con WhatsApp u otras herramientas?</summary><p>Se evalúa caso a caso según las APIs disponibles, permisos, requisitos de los proveedores y costos asociados. No damos por incluida una integración antes de revisarla.</p></details>
<details><summary>¿Los agentes pueden actuar sin supervisión?</summary><p>Definimos qué pueden responder o ejecutar y qué requiere aprobación humana. Los flujos pueden incluir derivación a una persona y registro de acciones. La IA puede equivocarse: los controles y las pruebas forman parte del alcance acordado.</p></details>
<details><summary>¿Pueden construir algo que no existe en el mercado?</summary><p>Sí. Podemos desarrollar software desde cero, como parte del CRM o como una aplicación independiente. Primero validamos el problema y la viabilidad; después definimos funcionalidades, integraciones, etapas y presupuesto contigo.</p></details>
<details><summary>¿Los agentes y automatizaciones están incluidos en el precio inicial?</summary><p>No se incluyen automáticamente. Se cotizan según los canales, integraciones, volumen y complejidad necesarios. La propuesta especifica desarrollo, proveedores, telefonía, consumo de IA y soporte para que conozcas los costos antes de comenzar.</p></details>
<details><summary>¿Y después de la entrega?</summary><p>La propuesta define los accesos, la documentación, el soporte y sus condiciones. También acordamos cómo se solicitan y cotizan nuevas funcionalidades.</p></details>
</div></div></section></main>
`+pie.replace('</body>',jsComun+'</body>');}
